apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
  namespace: todo-app-ns
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/TodoAppData
