apiVersion: v1
kind: Service
metadata:
  name: todo-webapp-svc
  namespace: todo-app-ns
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: web
  selector:
    app: todo-app
    tier: front
  type: LoadBalancer