apiVersion: v1
kind: Service
metadata:
  name: todo-api-svc
  namespace: todo-app-ns
spec:
  ports:
    - port: 8080
      targetPort: 80
      name: api
  selector:
    app: todo-app
    tier: back
  type: ClusterIP