apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-dep
  namespace: todo-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      tier: db
  template:
    metadata:
      labels:
        app: todo-app
        tier: db
    spec:
      containers:
      - name: todo-db
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 80  
        env:
        - name: POSTGRES_USER
          value: "dbuser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-api-db-secret
              key: dbpass
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: db-storage          
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: todo-app-pv-claim
