apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: todo-app-ns
spec:
  ports:
    - port: 1433
      targetPort: 1433
      name: db
  selector:
    app: todo-app
    tier: db
  type: ClusterIP